{
    "openapi": "3.0.0",
    "info": {
        "tilte": "Api de Manipulação de produtos",
        "description": "manipulação do banco de dados do LIMS",
        "contact": {
            "email": "rasolive@hotmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8089/v1",
            "description": "Url Local DEV"
        },
        {
            "url": "inserir url prd",
            "description": "Url Local PRD"
        }
    ],
    "paths": {
        "/health": {
            "get": {
                "summary": "Teste da aplicação",
                "description": "Essa rota realiza teste da aplicação",
                "tags": [
                    "Health"
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/contato": {
            "post": {
                "summary": "Formulário de contato",
                "description": "Essa rota realiza envio de mensagem para o administrador",
                "tags": [
                    "Formulário de contato"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/form"
                            },
                            "examples": {
                                "usuário": {
                                    "value": {
                                        "msg": "mensagem",
                                        "name": "nome",
                                        "email": "email@email.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Não foi possível enviar"
                    },
                    "200": {
                        "description": "Formulário enviado com sucesso"
                    }
                }
            }
        },
        "/auth/createUser": {
            "post": {
                "summary": "Cadastro de Usuário",
                "description": "Essa rota realiza o cadstro de usuário pelo próprio usuário",
                "tags": [
                    "Autenticação"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/users"
                            },
                            "examples": {
                                "create user": {
                                    "value": {
                                        "email": "email@email.com",
                                        "name": "nome",
                                        "password": "senha",
                                        "validPass": true
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Não foi possivel criar"
                    },
                    "412": {
                        "description": "Usuário já existe"
                    },
                    "200": {
                        "description": "Usuário criado"
                    }
                }
            }
        },
        "/auth/authenticate": {
            "post": {
                "summary": "Autenticação de usuário",
                "description": "Essa rota realiza autenticação do usuário",
                "tags": [
                    "Autenticação"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/users"
                            },
                            "examples": {
                                "usuário": {
                                    "value": {
                                        "email": "rasolive",
                                        "password": "0532291"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Usuário não encintrado no banco de dados"
                    },
                    "401": {
                        "description": "Senha incorreta"
                    },
                    "200": {
                        "description": "Usuário Autenticado"
                    }
                }
            }
        },
        "/email/forgotPassword": {
            "post": {
                "summary": "Reset de senha",
                "description": "Essa rota realiza o envio de uma nova senha por e-mail",
                "tags": [
                    "Autenticação"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/users"
                            },
                            "examples": {
                                "send e-mail": {
                                    "value": {
                                        "email": "email@email.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Usuário não encintrado no banco de dados"
                    },
                    "200": {
                        "description": "e-mail enviado"
                    }
                }
            }
        },
        "/fornecedores": {
            "post": {
                "summary": "Cadastro de Fornecedores",
                "description": "Essa rota realiza o cadstro de Fornecedores",
                "tags": [
                    "Fornecedores"
                ],
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/fornecedores"
                            },
                            "examples": {
                                "Criar Forneecedor": {
                                    "value": {
                                        "bairro": "bairro",
                                        "cep": "00000-000",
                                        "cidade": "cidade",
                                        "cnpj": "00.000.000/0000-03",
                                        "email": "email@email.com",
                                        "estado": "SP",
                                        "name": "nome do fornecedor",
                                        "numero": 1,
                                        "rua": "rua",
                                        "telefone": "(99) 9 9999-9999"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Não foi possivel criar"
                    },
                    "401": {
                        "description": "Token não disponibilizado/inválido"
                    },
                    "412": {
                        "description": "Fornecedor já existe"
                    },
                    "200": {
                        "description": "Fornecedore Cadastrado"
                    }
                }
            },
            "get": {
                "summary": "Lista de fornecedores cadastrados",
                "description": "Essa rota realiza a busca de fornecedores cadastrados no banco",
                "tags": [
                    "Fornecedores"
                ],
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Token não disponibilizado/inválido"
                    },
                    "200": {
                        "description": "ok"
                    }
                }
            }
        },
        "/fornecedores/{_id}": {
            "get": {
                "summary": "Busca de foencedor por \"id\"",
                "description": "Essa rota realiza a busca de fornecedor especifico",
                "tags": [
                    "Fornecedores"
                ],
                "parameters": [
                    {
                        "name": "_id",
                        "in": "path",
                        "description": "id do fornecedor",
                        "required": true
                    }
                ],
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Token não disponibilizado/inválido"
                    },
                    "200": {
                        "description": "ok"
                    }
                }
            },
            "put": {
                "summary": "Cadastro de Fornecedores",
                "description": "Essa rota realiza o cadstro de Fornecedores",
                "tags": [
                    "Fornecedores"
                ],
                "parameters": [
                    {
                        "name": "_id",
                        "in": "path",
                        "description": "id do fornecedor",
                        "required": true
                    }
                ],
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/fornecedores"
                            },
                            "examples": {
                                "Criar Forneecedor": {
                                    "value": {
                                        "bairro": "bairro",
                                        "cep": "00000-000",
                                        "cidade": "cidade",
                                        "email": "email@email.com",
                                        "estado": "SP",
                                        "name": "nome do fornecedor",
                                        "numero": 1,
                                        "rua": "rua",
                                        "telefone": "(99) 9 9999-9999"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Não foi possivel atualizar"
                    },
                    "401": {
                        "description": "Token não disponibilizado/inválido"
                    },
                    "200": {
                        "description": "Atualizado com sucesso"
                    }
                }
            },
            "delete": {
                "summary": "Deletar fornecedor por \"id\"",
                "description": "Essa rota deleta um fornecedor especifico",
                "tags": [
                    "Fornecedores"
                ],
                "parameters": [
                    {
                        "name": "_id",
                        "in": "path",
                        "description": "id do fornecedor",
                        "required": true
                    }
                ],
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Token não disponibilizado/inválido"
                    },
                    "200": {
                        "description": "ok"
                    }
                }
            }
           
        }
    },
    "components": {
        "schemas": {
            "users": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "Number"
                    },
                    "active": {
                        "type": "Boolean"
                    },
                    "name": {
                        "type": "String"
                    },
                    "email": {
                        "type": "String"
                    },
                    "password": {
                        "type": "String"
                    },
                    "validPass": {
                        "type": "Boolean"
                    },
                    "role": {
                        "type": "Array"
                    },
                    "createdBy": {
                        "type": "String"
                    },
                    "updatedBy": {
                        "type": "String"
                    }
                }
            },
            "form": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "Number"
                    },
                    "active": {
                        "type": "Boolean"
                    },
                    "name": {
                        "type": "String"
                    },
                    "email": {
                        "type": "String"
                    },
                    "msg": {
                        "type": "String"
                    }
                }
            },
            "fornecedores": {
                "type": "object",
                "properties": {
                    "_id": {
                        "type": "Number"
                    },
                    "active": {
                        "type": "Boolean"
                    },
                    "name": {
                        "type": "String"
                    },
                    "rua": {
                        "type": "String"
                    },
                    "numero": {
                        "type": "String"
                    },
                    "bairro": {
                        "type": "String"
                    },
                    "cidade": {
                        "type": "String"
                    },
                    "estado": {
                        "type": "String"
                    },
                    "cep": {
                        "type": "String"
                    },
                    "telefone": {
                        "type": "String"
                    },
                    "email": {
                        "type": "String"
                    },
                    "cnpj": {
                        "type": "String"
                    },
                    "createdBy": {
                        "type": "String"
                    },
                    "updatedBy": {
                        "type": "String"
                    }
                }
            }
        },
        "securitySchemes": {
            "JWT": {
                "description": "",
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"
            }
        }
    }
}